{{ $name := .Values.name }}
{{ $image := .Values.image }}
{{ $tag := .Values.tag }}
{{ $jobPostingGrpcEndpoint := .Values.jobPostingGrpcEndpoint }}
{{ $reviewGrpcEndpoint := .Values.reviewGrpcEndpoint }}

{{- range $i, $site := .Values.sites }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{$name}}-{{$site}}
spec:
  schedule: "09 19 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{$name}}
              image: {{ $image }}:{{ $tag }}
              args: ["-site={{ $site }}"]
              env:
                - name: JOB_POSTING_GRPC_ENDPOINT
                  value: "{{$jobPostingGrpcEndpoint}}"
                - name: REVIEW_GRPC_ENDPOINT
                  value: "{{$reviewGrpcEndpoint}}"
  concurrencyPolicy: Forbid
---
{{- end }}
