---
- name: Install k8s
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Disable UFW
      shell: ufw disable
    - name: Set kernel modules for Kubernetes
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Disable swap
      lineinfile:
        path: /etc/fstab
        regexp: '\sswap\s'
        line: '#\g<0>'
        backrefs: yes

    - name: Load kernel modules
      shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Apply sysctl settings
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Reload sysctl
      shell: sysctl --system

    - name: Install dependencies for Kubernetes
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
