---
- name: Install k8s
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Make dir /etc/apt/keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Check if Kubernetes GPG key exists
      stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: gpg_key_status
    - name: Add Kubernetes GPG key and repository
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes
      when: not gpg_key_status.stat.exists

    - name: Add Kubernetes repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet=1.29.13-1.1
          - kubeadm=1.29.13-1.1
          - kubectl=1.29.13-1.1
        state: present
        update_cache: yes

    - name: Remove containerd default config
      file:
        path: /etc/containerd/config.toml
        state: absent
      register: remove_containerd_config

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
      when: remove_containerd_config.changed
