---
- hosts: all
  connection: local
  serial: 1
  gather_facts: no
  tasks:
    - name: Scan the host key
      command: ssh-keyscan -t ecdsa {{ ansible_host }}
      register: keyscan
    - name: Add the host key to the known_hosts file
      lineinfile:
        name: ~/.ssh/known_hosts
        create: yes
        line: "{{ item }}"
      with_items:
        - "{{ keyscan.stdout_lines }}"
