apiVersion: v1
kind: Service
metadata:
  name: {{.Values.provider.name}}
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.provider.grpcPort}}
      targetPort: {{.Values.provider.grpcPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.scanner.name}}
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.scanner.grpcPort}}
      targetPort: {{.Values.scanner.grpcPort}}
