apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      restartPolicy: Always
      containers:
        - name: {{.Values.name}}
          image: {{ .Values.image }}:{{ .Values.tag }}
          env:
            - name: MONGO_URI
              value: {{.Values.mongoUri}}
            - name: DB_NAME
              value: {{.Values.dbName}}
            - name: DB_USERNAME
              value: {{.Values.dbUsername}}
            - name: DB_PASSWORD
              value: {{.Values.dbPassword}}
            - name: PROVIDER_GRPC_PORT
              value: "{{.Values.provider.grpcPort}}"
            - name: SCANNER_GRPC_PORT
              value: "{{.Values.scanner.grpcPort}}"
            - name: RESTAPI_GRPC_PORT
              value: "{{.Values.restapi.grpcPort}}"
          ports:
            - containerPort: {{.Values.provider.grpcPort}}
            - containerPort: {{.Values.scanner.grpcPort}}
            - containerPort: {{.Values.restapi.grpcPort}}
