apiVersion: v1
kind: Service
metadata:
  name: {{.Values.provider.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.provider.grpcPort}}
      targetPort: {{.Values.provider.grpcPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.scanner.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.scanner.grpcPort}}
      targetPort: {{.Values.scanner.grpcPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.restApi.name}}
spec:
  type: NodePort
  selector:
    app: {{.Values.name}}
  ports:
    - port: {{.Values.restApi.apiPort}}
      targetPort: {{.Values.restApi.apiPort}}
      nodePort: {{.Values.restApi.nodePort}}
