---
- name: Set kubecfg secret
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Get kubeconfig
      shell: |
        cat /etc/kubernetes/admin.conf |  yq eval '.clusters[] |= select(.name == "kubernetes") |= .cluster.server = "https://{{ ansible_host }}:6443"'
      register: kubeconfig
    - name: Set kubecfg secret
      command: |
        aws secretsmanager put-secret-value --secret-id {{secret_id}} --secret-string "{{kubeconfig.stdout}}"
