apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{.Values.name}}
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{.Values.name}}
              image: {{ .Values.image }}:{{ .Values.tag }}
              env:
                - name: MONGO_URI
                  value: {{.Values.mongoUri}}
                - name: DB_NAME
                  value: {{.Values.dbName}}
                - name: DB_USERNAME
                  value: {{.Values.dbUsername}}
                - name: DB_PASSWORD
                  value: {{.Values.dbPassword}}
                - name: GRPC_ENDPOINT
                  value: "{{.Values.grpcEndpoint}}"
                - name: POST_LOG_URL
                  value: "{{.Values.postLogUrl}}"
              # 애플리케이션 실행 설정
  concurrencyPolicy: Forbid # 이전 작업이 종료될 때까지 다음 작업이 시작되지 않음
