{{ $name := .Values.name }}
{{ $image := .Values.image }}
{{ $tag := .Values.tag }}
{{ $grpcEndpoint := .Values.grpcEndpoint }}
{{ $postLogUrl := .Values.postLogUrl }}

{{- range $i, $site := .Values.sites }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{$name}}-{{$site}}
spec:
  schedule: "12 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{$name}}
              image: {{ $image }}:{{ $tag }}
              args: ["-site={{ $site }}"]
              env:
                - name: GRPC_ENDPOINT
                  value: "{{$grpcEndpoint}}"
                - name: POST_LOG_URL
                  value: "{{$postLogUrl}}"
  concurrencyPolicy: Forbid
---
{{- end }}
