apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  type: NodePort
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.apiPort}}
      targetPort: {{.Values.apiPort}}
      nodePort: {{.Values.nodePort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mailer.name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.mailer.grpcPort}}
      targetPort: {{.Values.mailer.grpcPort}}
