nodeSelector:
  - key: "usage"
    value: "monitoring"
tolerations:
  - key: "usage"
    operator: "Equal"
    value: "monitoring"
    effect: "PreferNoSchedule"
initialAdminPassword: "frjeigogFROiwfr04435!@#$%"
