name: ${charts.log_system.name}
targetNamespace: ${charts.namespace}

opensearchDashboard:
  name: "${charts.log_system.dashboard_name}"
  port: ${charts.log_system.dashboard_port}

opensearch:
  name: ${charts.log_system.opensearch_name}

fluentbit:
  name: ${charts.log_system.name}-fluentbit

kubeLogsDir: /var/log/containers
nodeSelector:
  - key: "usage"
    value: "monitoring"
tolerations:
  - key: "usage"
    operator: "Equal"
    value: "monitoring"
    effect: "PreferNoSchedule"
initialAdminPassword: #known after the deployment

