name: ${charts.log_system.name}
targetNamespace: ${charts.namespace}

kubeLogsDir: /var/log/containers
nodeSelector:
  - key: "usage"
    value: "monitoring"
tolerations:
  - key: "usage"
    operator: "Equal"
    value: "monitoring"
    effect: "PreferNoSchedule"
initialAdminPassword: #known after the deployment
