name: log-system
targetNamespace: careerhub

kubeLogsDir: /var/log/containers
nodeSelector:
  - key: "usage"
    value: "monitoring"
tolerations:
  - key: "usage"
    operator: "Equal"
    value: "monitoring"
    effect: "PreferNoSchedule"
initialAdminPassword: #known after the deployment
