name: log-system
targetNamespace: careerhub

opensearchDashboard:
  name: "log-system-opensearch-dashboard"

opensearch:
  name: log-system-opensearch

fluentbit:
  name: log-system-fluentbit

kubeLogsDir: /var/log/containers
nodeSelector:
  - key: "usage"
    value: "monitoring"
tolerations:
  - key: "usage"
    operator: "Equal"
    value: "monitoring"
    effect: "PreferNoSchedule"
initialAdminPassword: #known after the deployment
