name: posting-service
image: #known after the deployment
tag: #known after the deployment
dbName: careerhub
postLogUrl: http://log-api:8080/logs
mongoUri: #known after the deployment
dbUsername: #known after the deployment
dbPassword: #known after the deployment
provider:
  name: provider-grpc
  grpcPort: 50051
scanner:
  name: skillscanner-grpc
  grpcPort: 50052
restApi:
  name: rest-api
  apiPort: 8080
  nodePort: 30000
