name: ${charts.data_provider.name}
image: #known after the deployment
tag: #known after the deployment
jobPostingGrpcEndpoint: ${charts.data_processor.provider.name}:${charts.data_processor.provider.grpc_port}
reviewGrpcEndpoint: ${charts.review_service.provider.name}:${charts.review_service.provider.grpc_port}
sites:
%{ for site in charts.data_provider.sites ~}
  - ${site}
%{ endfor ~}
