name: data-processor
image: 986069063944.dkr.ecr.ap-south-1.amazonaws.com/dev-careerhub-processor-ecr
tag: latest
dbName: careerhub
postLogUrl: http://log-api:8080/logs
mongoUri: #known after the deployment
dbUsername: #known after the deployment
dbPassword: #known after the deployment
provider:
  name: provider-grpc
  grpcPort: 50051
scanner:
  name: scanner-grpc
  grpcPort: 50052
restApi:
  name: rest-api
  apiPort: 8080
  nodePort: 30000
