name: data-processor
image: 986069063944.dkr.ecr.ap-south-1.amazonaws.com/dev-careerhub-processor-ecr
tag: latest
grpcPort: 50051
mongoUri: mongodb+srv://dev-careerhub-jobpostin.mok9txh.mongodb.net
postLogUrl: http://log-api:8080/logs
