---
- name: Install docker
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Check if Docker GPG key exists
      stat:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
      register: gpg_key_status
    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes
      when: not gpg_key_status.stat.exists

    - name: Get the architecture
      shell: dpkg --print-architecture
      register: dpkg_arch
      changed_when: false

    - name: Get the release codename
      shell: lsb_release -cs
      register: lsb_release
      changed_when: false

    - name: Add Docker repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ dpkg_arch.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable

    - name: Install Docker
      apt:
        name:
          - docker-ce=5:27.5.0-1~ubuntu.20.04~focal
          - docker-ce-cli=5:27.5.0-1~ubuntu.20.04~focal
          - containerd.io=1.7.25-1
        state: present
        update_cache: yes
      register: install_docker

    - name: Configure Docker daemon
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
              "data-root": "/data/docker"
          }
      register: configure_docker_daemon

    - name: Reload Docker daemon
      systemd:
        daemon_reload: yes
      when: configure_docker_daemon.changed or install_docker.changed
      register: reload_docker_daemon
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
      when: reload_docker_daemon.changed
